# Welcome to the config for command blocker
# This has support for the wildcard *
blocked:
  - /mctop *
  - /baltop *
  - /balancetop *
  
# This is the message sent to the player when he tries to perform a blocked command
# %c% is replaced with the command
# Set to null to disable
message: "&cThat command, %c%, is temporarily disabled!"